<?php declare(strict_types=1);

namespace Hhag\ThreesixtyViewer;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\ActivateContext;
use Shopware\Core\Framework\Plugin\Context\DeactivateContext;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;
use Shopware\Core\Framework\Plugin\Context\UpdateContext;
use Hhag\ThreesixtyViewer\Installer\Installer as InstallHelper;

class HhagThreesixtyViewer extends Plugin
{


    public function install(InstallContext $installContext): void
    {
        $installer = new InstallHelper($this->container, $installContext->getContext());
        $installer->createMediaFolder();

        parent::install($installContext); // TODO: Change the autogenerated stub
    }

    public function uninstall(UninstallContext $uninstallContext): void
    {
        parent::uninstall($uninstallContext); // TODO: Change the autogenerated stub

        if(!$uninstallContext->keepUserData()){
            $connection = $this->container->get(Connection::class);

            $connection->executeStatement('DROP TABLE IF EXISTS `hhag_media_threesixty_data`');
        }
    }

    public function update(UpdateContext $updateContext): void
    {
        parent::update($updateContext); // TODO: Change the autogenerated stub
    }

}